### ISSUE TITLE
PDF Viewer lows down image quality

### ISSUE THREAD

**Issue by angelesbri1s** [densitydesign/placplac#139]
Il pdf viewer abbassa considerablemente la resoluzione dei file caricati , siano di testo, vettori o imagine. L'idea è che questo non succeda perchè ci serve per far vedere visualizzazioni, diagrammi, documenti, fotografie con i loro dettagli.
<img width="2048" alt="Screenshot 2022-06-10 at 16 00 29" src="https://user-images.githubusercontent.com/10846801/173082765-fe7bf772-8c55-45dc-ad53-c8a6bf73b38d.png">
(screenshot pdf viewer su placplac)

<img width="2048" alt="Screenshot 2022-06-10 at 16 00 52" src="https://user-images.githubusercontent.com/10846801/173082837-81907d7e-3c9d-478d-ae5a-523aa886fcfc.png">
screenshot del documento pdf aperto in pdf

@gianpieropa

**Comment by gianpieropa** [comment]
Could you send me this pdf file ?

**Comment by angelesbri1s** [comment]
> ecco il pdf che abbiamo usato
[video-tag-corporate-all.pdf](https://github.com/densitydesign/placplac/files/9100085/video-tag-corporate-all.pdf)
