### ISSUE TITLE
SVG images look pixelate

### ISSUE THREAD

**Issue by angelesbri1s** [densitydesign/placplac#140]
L'immagine svg che vengono per default sul home si vedono pixelated. Non capiamo come mai dato che l'immagine sono svg e questo non dovrebbe succedere.
<img width="305" alt="Screenshot 2022-06-13 at 10 36 47" src="https://user-images.githubusercontent.com/10846801/173314084-fee54bb4-89d5-4098-a347-b06cc1cda208.png">

**Comment by gianpieropa** [comment]
Usiamo p5.js per l'animazione nell'homepage e leggendo le docs sembra non abbiano il supporto agli svg, i quali vengono convertiti in semplici immagini. Dovremmo provare caricando dei file png con qualità più alta e vedere come vengono scalati da p5js
