### ISSUE TITLE
add columns in experiment grid

### ISSUE THREAD

**Issue by angelesbri1s** [densitydesign/placplac#146]
@gianpieropa 
1. L'icona per aggiungere colonne rimane "nascosta" dietro il hover del mouse quando è sul box, difficoltando la possibilità di cliccare l'icona. Questo acade quando il box ha già stato popolato di contenuto, quando è vuoto non accade.
<img width="381" alt="Captura de pantalla 2022-06-20 a las 14 27 19" src="https://user-images.githubusercontent.com/10846801/174601461-15ae3dae-54b2-4f50-b1b5-cec913615885.png">
L'icona dovrebbe rimanere sopra la evvidenziazione del hover del box.

2. L'icono è poco chiara, abbiamo come suggerimento questa da material design
<img width="75" alt="Captura de pantalla 2022-06-20 a las 14 37 29" src="https://user-images.githubusercontent.com/10846801/174603468-e1609527-3714-4c8b-b936-0b9f69ad1032.png">

<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M11,2A2,2 0 0,1 13,4V20A2,2 0 0,1 11,22H2V2H11M4,10V14H11V10H4M4,16V20H11V16H4M4,4V8H11V4H4M15,11H18V8H20V11H23V13H20V16H18V13H15V11Z" />
</svg>

3. La colonna viene aggiunta solo a lato sinistro sull'ultimo box. Sarebbe el caso di dare possibilità di scegliere a quale lato e dove aggiungere. Se potrebbe aggiungere l'icona e la possibilità di aggiungere su qualsiasi box? (massimo di colonne sempre 4).

**Comment by gianpieropa** [comment]
Per l'icona non ci sono problemi, giratemi il nome dell'icona altrimenti mi risulta difficile cercarla tra le migliaia che ce ne sono. Per la scelta della posizione in cui aggiungere la colonna non credo sia necessario dato che le colonne si possono spostare.
