### ISSUE TITLE
Routing problems in Glossary

### ISSUE THREAD

**Issue by iosonosempreio** [densitydesign/placplac#158]
Glossary pages (pills) are not working when built and hosted remotely.

To reproduce:

1. go to http://labs.densitydesign.org/algocount
2. click on Glossary
3. click on a Pill

<img width="928" alt="Screenshot 2022-06-24 at 11 34 09" src="https://user-images.githubusercontent.com/7115395/175507983-aed4b666-de51-44c0-8935-d228274ef6be.png">

Additionally, the loading of this URL fails: http://labs.densitydesign.org/algocount/glossary

<img width="1728" alt="Screenshot 2022-06-24 at 11 33 49" src="https://user-images.githubusercontent.com/7115395/175507934-8703f9b7-3cea-4c16-a487-fecd320d3242.png">

**Comment by gianpieropa** [comment]
I tried to reproduce the problem but this does not depend from the project, it depends on the configuration of the server. If you try to serve to project using a simple web server like [serve](https://www.npmjs.com/package/serve) it will work flawlessly
