### ISSUE TITLE
Project import fails

### ISSUE THREAD

**Issue by iosonosempreio** [densitydesign/placplac#160]
Steps to reproduce:
1. Export a project
2. Upload a project
3. "something went wrong"

![2022-06-24 11 49 00](https://user-images.githubusercontent.com/7115395/175510638-686982ba-1661-488e-bc63-29b38c63bf53.jpg)

**Comment by gianpieropa** [comment]
I need the zip file of the exported project, to reproduce the import fail. Thank you

**Comment by bea92** [comment]
[here you can find a sample .zip folder](https://drive.google.com/drive/folders/1Ch32y5_Nx6lbW2qmEWHW_IWcjuepjVaP?usp=sharing)

**Comment by gianpieropa** [comment]
Thank you for the file, the issue is solved!

**Comment by angelesbri1s** [comment]
This issue it's not been solved. Even if I try uploading the same project (.zip) used before.
