### ISSUE TITLE
Breadcrumbs and UTF8

### ISSUE THREAD

**Issue by bea92** [densitydesign/placplac#178]
When adding a reference with a "space", in the breadcrumbs, it appears as £&nsbp</". Could you fix it?
<img width="295" alt="Screenshot 2022-08-02 at 16 11 15" src="https://user-images.githubusercontent.com/25208955/182405663-3c8ae780-58a7-47e4-b561-1c26dcdf552a.png">

**Comment by angelesbri1s** [comment]
lo "space" ha stato risolto ma compaiono altre aspetti che non devono comparire come ad esempio il "bold" di una reference. Mi spiego meglio (seguendo l'immagine aggiunta): se la reference il nome degli autori con bold, nel titolo de la pagina di editing della ref viene fuori "strong Id Docs...". Dovrebbe essere visibile solo i'inizio del nome della reference e non su stilo. 

<img width="830" alt="Screenshot 2022-10-07 at 14 43 24" src="https://user-images.githubusercontent.com/10846801/194556450-c80b5df3-6531-467e-a997-aabf24320184.png">
